path:
- data.csv
sae_id:
- blocks.0.hook_mlp_out
- blocks.1.hook_mlp_out
- blocks.2.hook_mlp_out
- blocks.3.hook_mlp_out
- blocks.4.hook_mlp_out
- blocks.5.hook_mlp_out
- blocks.6.hook_mlp_out
- blocks.7.hook_mlp_out
- blocks.8.hook_mlp_out
- blocks.9.hook_mlp_out
- blocks.10.hook_mlp_out
- blocks.11.hook_mlp_out


model:
- release: gpt2-small-mlp-tm
  index: v4_pileval_gpt2
  model_name: gpt2-small
