releases:
  - gpt2-small-res-jb
  - gpt2-small-hook-z-kk
  - gpt2-small-mlp-tm
  - gpt2-small-res-jb-feature-splitting
  - gpt2-small-resid-post-v5-32k
  - gpt2-small-resid-post-v5-128k
  - gemma-2b-res-jb
  - gemma-2b-it-res-jb
  - mistral-7b-res-wg
  - gpt2-small-resid-mid-v5-32k
  - gpt2-small-resid-mid-v5-128k
  - gpt2-small-mlp-out-v5-32k
  - gpt2-small-mlp-out-v5-128k
  - gpt2-small-attn-out-v5-32k
  - gpt2-small-attn-out-v5-128k
  - gemma-scope-2b-pt-res
  - gemma-scope-2b-pt-res-canonical
  - gemma-scope-2b-pt-mlp
  - gemma-scope-2b-pt-mlp-canonical
  - gemma-scope-2b-pt-att
  - gemma-scope-2b-pt-att-canonical
  - gemma-scope-9b-pt-res
  - gemma-scope-9b-pt-res-canonical
  - gemma-scope-9b-pt-att
  - gemma-scope-9b-pt-att-canonical
  - gemma-scope-9b-pt-mlp
  - gemma-scope-9b-pt-mlp-canonical
  - gemma-scope-9b-it-res
  - gemma-scope-9b-it-res-canonical
  - gemma-scope-27b-pt-res
  - gemma-scope-27b-pt-res-canonical
  - pythia-70m-deduped-res-sm
  - pythia-70m-deduped-mlp-sm
  - pythia-70m-deduped-att-sm
  - gpt2-small-res_sll-ajt
  - gpt2-small-res_slefr-ajt
  - gpt2-small-res_scl-ajt
  - gpt2-small-res_sle-ajt
  - gpt2-small-res_sce-ajt
  - gpt2-small-res_scefr-ajt
  - sae_bench_gemma-2-2b_sweep_standard_ctx128_ef2_0824
  - sae_bench_gemma-2-2b_sweep_standard_ctx128_ef8_0824
  - sae_bench_gemma-2-2b_sweep_topk_ctx128_ef2_0824
  - sae_bench_gemma-2-2b_sweep_topk_ctx128_ef8_0824
  - sae_bench_pythia70m_sweep_gated_ctx128_0730
  - sae_bench_pythia70m_sweep_panneal_ctx128_0730
  - sae_bench_pythia70m_sweep_standard_ctx128_0712
  - sae_bench_pythia70m_sweep_topk_ctx128_0730
  - llama-3-8b-it-res-jh
